vich_uploader:
    db_driver: orm
    mappings:
        temoignages:
            uri_prefix: /images/temoignages
            upload_destination: '%kernel.project_dir%/public/images/temoignages'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        services_graphisme:
            uri_prefix: /images/services_graphisme
            upload_destination: '%kernel.project_dir%/public/images/services_graphisme'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        identite_du_site:
            uri_prefix: /images/identite_du_site
            upload_destination: '%kernel.project_dir%/public/images/identite_du_site'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        avantage_site:
            uri_prefix: /images/avantage_site
            upload_destination: '%kernel.project_dir%/public/images/avantage_site'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        image_Graph:
            uri_prefix: /images/image_Graph
            upload_destination: '%kernel.project_dir%/public/images/image_Graph'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        image_slogan:
            uri_prefix: /images/image_slogan
            upload_destination: '%kernel.project_dir%/public/images/image_slogan'
            namer: Vich\UploaderBundle\Naming\UniqidNamer 

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        services_web:
            uri_prefix: /images/services_web
            upload_destination: '%kernel.project_dir%/public/images/services_web'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        equipes:
            uri_prefix: /images/equipes
            upload_destination: '%kernel.project_dir%/public/images/equipes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        articles:
            uri_prefix: /images/articles
            upload_destination: '%kernel.project_dir%/public/images/articles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        sliders:
            uri_prefix: /images/sliders
            upload_destination: '%kernel.project_dir%/public/images/sliders'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        logo_Graph_client:
            uri_prefix: /images/logo_Graph_client
            upload_destination: '%kernel.project_dir%/public/images/logo_Graph_client'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        logo_Graph_filgrame:
            uri_prefix: /images/logo_Graph_filgrame
            upload_destination: '%kernel.project_dir%/public/images/logo_Graph_filgrame'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        logo_Graph_finale:
            uri_prefix: /images/logo_Graph_finale
            upload_destination: '%kernel.project_dir%/public/images/logo_Graph_finale'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        carteVisite_client:
            uri_prefix: /images/carteVisite_client
            upload_destination: '%kernel.project_dir%/public/images/carteVisite_client'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        carteVisite_filigra:
            uri_prefix: /images/carteVisite_filigra
            upload_destination: '%kernel.project_dir%/public/images/carteVisite_filigra'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        carteVisite_finale:
            uri_prefix: /images/carteVisite_finale
            upload_destination: '%kernel.project_dir%/public/images/carteVisite_finale'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        affiche_finale:
            uri_prefix: /images/affiche_finale
            upload_destination: '%kernel.project_dir%/public/images/affiche_finale'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        affiche_filigrame:
            uri_prefix: /images/affiche_filigrame
            upload_destination: '%kernel.project_dir%/public/images/affiche_filigrame'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 